spring:
  application:
    name: movies
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/moviesdb
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
server:
  port: 8020
  servlet:
    context-path: /api
